Clerk login implement
thekalamanchofficial/kalamanch pull request #1
Opened 2024-10-01 09:32 UTC by yashrajoria3

- create ui for login page
- implemented clerk login system with option for google auth 
- added toast for alerting user for warning and impending requests
- initialized prisma as orm
- added backend api to register new user on mongodb

2024-10-02 08:37 UTC, thekalamanchofficial requested changes

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/_utils/formValidate.ts
> +  // Email validation
move all this to a form schema using yup. Use react hook form to render components and display the form errors received from yup.

Create a separate schema folder for it

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/layout.tsx
> -  title: "Create T3 App",
add appropriate metadata instead of removing it

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/layout.tsx
> +          <ToastContainer
use toast only for success and error message. use loader/spinner instead.

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/layout.tsx
> +          <ToastContainer
fine for now

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +  const onSubmit = async (data: any) => {
remove unised data args. Give appropriate type to onSubmit function

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +  const onSubmit = async (data: any) => {
move onSubmit function after login

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +  const onSubmit = async (data: any) => {
add await

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +    let email = getValues("email");
use const for email and password

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +  } = useForm();
create a custom hook to return formState with relative types. This will fix getValues `any` data type

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +          if (signInAttempt.status === "complete") {
use enum for sign in status

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +            throw new Error("Login attempt was not completed successfully."); // Throw an error to trigger the error toast
move all static text to a static text file

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +            <svg
move all svg and images to assets folder and import as react component from there

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +                if (!isLoaded) return;
create a click handler for the onclick and move the logic there

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +                setIsSignUp(true);
instead of boolean, setup enum for different sections of forms and set the sections accordingly

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +              if (!isLoaded) return;
move to specific handler

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +                  <input
use react-hook-form controller to render inputs

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +                  <h1
use link instead of h1

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +import { useState, KeyboardEvent, ChangeEvent, FocusEvent } from "react";
```
import {
  useState,
  type KeyboardEvent,
  type ChangeEvent,
  type FocusEvent,
} from "react";
```

use this

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +    if (!e || !e.key || e.target) return;
use a library instead to ease up the work

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +        setOtp((prevOtp) => [
give a type to setOtp

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +    "Animals",
make enum for all these interests and create array of enum. Keep this array of enum as a const in some config file

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +    {
create a type for information and use array of information exactly like interests

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +    register,
create a custom hook for this useForm

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +    const currentInterests = getValues("interests");
create appropriate schema for the form. This will fix the any type lint error

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +  const next = () => {
call it onNextClick

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +    if (formNo === 1) {
use enum for various form sections

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +    } catch (err: any) {
remove any

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +                        document.getElementById("profile")?.click()
never use document.getelementbyid

2024-10-02 08:37 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +            {formNo === 2 && (
use ternary operator instead of short circuit

2024-10-02 08:40 UTC, thekalamanchofficial requested changes

2024-10-02 08:40 UTC, thekalamanchofficial commented on src/server/routers/user.ts
> +import { z } from "zod";
use `yup` inplace of `zod`

2024-10-02 21:09 UTC, yashrajoria3 commented on src/app/layout.tsx
> -  title: "Create T3 App",
added a relevant metadata

2024-10-02 21:22 UTC, yashrajoria3 commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +            <svg
created a seperate folder for all svgs

2024-10-02 21:23 UTC, yashrajoria3 commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +    if (!e || !e.key || e.target) return;
imported react-otp-input library

2024-10-06 09:22 UTC, thekalamanchofficial requested changes

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/_components/SignUp/Details.tsx
> +                  {/* <input
Remove commented code and console logs from code

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/_components/SignUp/Details.tsx
> +                  {/* <span className="absolute right-0 top-2 inline-flex items-center rounded-s-md px-3 text-sm text-gray-900">
Remove commented code

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/_components/writingPad/writingPad.tsx
> +      {/* <h1>{JSON.stringify(users.data)}</h1> */}
Remove commented code

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/_components/static/staticText.ts
> +  FORM_STEP3: "Select Role",
There are more static texts to be moved here

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-in/[[...sign-in]]/page.tsx
> +          pending: "Logging in, please wait...", // Message while the promise is pending
Move all the static texts to static file

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +                  width="40"
Move this svg to assets folder

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/assets/static.ts
> +export const enum signUpFormStages {
Use pascal case for enum

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/assets/static.ts
> +export const interestsArray = [
These seem duplicated

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-in/_schema/schema.ts
> +    .email("Invalid email format")
move to static file

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +              await addUserToDB();
```
const resp = await addUserToDB();
if(resp.status==='ok'){
router.push('/')
}else{
handle error
}
```

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +        console.error(JSON.stringify(signUpAttempt, null, 2));
handle error in more better way

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +                <svg
move svg to assets

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/[[...sign-up]]/page.tsx
> +                <svg
move svg to assets

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/_config/config.ts
> +  complete = "complete",
use caps

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/_config/config.ts
> +
type = string[]

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/_config/config.ts
> +export const ROLES_INFORMATION = [
define a type

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/_types/types.ts
> +export type FormDataInterest = {
FormDataInterest = string[]

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/assets/svg/svg.tsx
> +export const GoogleSVG = () => {
Paste the svg file directly in assets folder. Import the svg as react component

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/server/routers/user.ts
> +// export const userRouter = router({
remove zod code

2024-10-06 09:22 UTC, thekalamanchofficial commented on tailwind.config.ts
> +        "brand-primary": "#260EB9",
take reference from design system

2024-10-06 09:22 UTC, thekalamanchofficial commented on src/app/sign-up/_config/config.ts
> +export const ROLES_INFORMATION = [
type ROLES_TYPE = {
title: string;
description: string;
key: string;
}

2024-10-07 15:24 UTC, thekalamanchofficial approved these changes, later dismissed
lg

2024-10-07 15:52 UTC, thekalamanchofficial approved these changes

2024-10-07 17:13 UTC, helloManojkr approved these changes

2024-10-07 17:13 UTC, merged