Post Fetching and LIke Button functionality
thekalamanchofficial/kalamanch pull request #12
Opened 2024-12-06 13:07 UTC by yashrajoria3

Api for fetching post from backend, and like button functionality

2024-12-09 06:28 UTC, thekalamanchofficial requested changes

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  const { user } = useClerk();
move all the logic to custom hook. Name it useMyFeedPage

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  const [skip, setSkip] = useState(0);
use custom component for tab created. use enums insead of indexes

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  } = postMutation.getPosts.useQuery(
try to fetch 15 posts initially, then on intervals of 200vh fetch 5 more posts

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  const [isLoadingInitial, setIsLoadingInitial] = useState(true);
try using just the constant isLoading from useQuery exported from the custom hook

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  const [isLoadingMore, setIsLoadingMore] = useState(false);
for isLoadingMore use the skip value and return from hook

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +    { skip, limit: 3 },
use constants for skip and limit from common config

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +      enabled: !!user?.primaryEmailAddress,
use  enabled: !!user?.primaryEmailAddress?.emailAddress,

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +          prevPosts.map((post) =>
keep the logic of setpost outside the setstate and pass the value to it

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +        setPosts((prevPosts) =>
take the logic out

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +    if (postData) {
move the logic to custom hook. Use useMemo to store and update the state values. Try to get rid of the useEffect

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  useEffect(() => {
try to get rid of the useeffect

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  useEffect(() => {
create a common hook for scroll listener which will accept a callback and pass the handleScroll to the hook

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +      {postData?.length != 0 ? (
simplify the logic something like this,

 const renderUI = useMemo(()=>{
    if(tab === 0){
      
    }
    if(tab === 1){}
  },[])

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +              <CircularProgress />
use title prop in CircularProgress

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +          <Typography> No Posts Found</Typography>
create common components for loading and no data scenarios

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/types/types.ts
> +  thumbnail_picture: string[];
use camel casing

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/_components/CommentSection/CommentSection.tsx
> +    if (newComment?.trim().length > 1000) {
dont keep any limits to comment length. Show indentation for comments

2024-12-09 06:28 UTC, thekalamanchofficial commented on src/app/_components/commentCard/CommentCard.tsx
> +              2 days ago
remove hardcode value, use created time

2024-12-09 15:47 UTC, yashrajoria3 commented on src/app/(with-sidebar)/myfeed/page.tsx
> +              <CircularProgress />
title prop does not show title

2024-12-11 13:34 UTC, yashrajoria3 commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  } = postMutation.getPosts.useQuery(
same issue as before, 200vh condition met before the posts are shown on screen , making the next call before

2024-12-12 15:40 UTC, thekalamanchofficial commented on package.json
> +    "date-fns": "^4.1.0",
Why was this new package added. We already have dayjs in this project

2024-12-12 15:42 UTC, thekalamanchofficial commented on package.json
> +    "install": "^0.13.0",
purpose of this library?

2024-12-12 15:42 UTC, thekalamanchofficial commented on package.json
> +    "npm": "^10.9.2",
Did we update npm ? Why?

2024-12-12 15:42 UTC, thekalamanchofficial commented on package.json
> +    "react-spring": "^9.7.4",
Why did we add this?

2024-12-12 15:42 UTC, thekalamanchofficial commented on prisma/schema.prisma
> +// datasource db {
Remove all these commented lines

2024-12-12 15:43 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myProfile/mocks/myProfileMock.ts
> +      thumbnail_picture: ["https://picsum.photos/seed/post1/800/600"],
Haven't fixed this naming

2024-12-12 15:44 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myProfile/page.tsx
> +  const [posts, setPosts] = useState<ArticlesList[]>([]);
all this should be moved to hook. Let's do that as part of separate PR

2024-12-12 15:47 UTC, thekalamanchofficial commented on src/app/_components/CommentSection/CommentCard.tsx
> +const CommentCard: React.FC<commentCardProps> = ({
Did we need these comment components?

2024-12-12 15:50 UTC, thekalamanchofficial commented on src/server/routers/post.ts
> +  // getPosts: publicProcedure
remove these commented line

2024-12-12 15:55 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/page.tsx
> +  useEffect(() => {
this is still pending

2024-12-12 15:56 UTC, thekalamanchofficial commented on src/app/(with-sidebar)/myfeed/types/types.ts
> +  thumbnail_picture: string[];
still pending

2024-12-13 09:22 UTC, yashrajoria3 commented on src/app/(with-sidebar)/myfeed/types/types.ts
> +  thumbnail_picture: string[];
done

2024-12-13 09:22 UTC, yashrajoria3 commented on package.json
> +    "date-fns": "^4.1.0",
deleted

2024-12-13 09:22 UTC, yashrajoria3 commented on package.json
> +    "install": "^0.13.0",
removed

2024-12-13 09:26 UTC, yashrajoria3 commented on package.json
> +    "npm": "^10.9.2",
deleted

2024-12-13 09:27 UTC, yashrajoria3 commented on package.json
> +    "react-spring": "^9.7.4",
removed

2024-12-13 09:27 UTC, yashrajoria3 commented on prisma/schema.prisma
> +// datasource db {
done

2024-12-13 09:27 UTC, yashrajoria3 commented on src/app/(with-sidebar)/myProfile/mocks/myProfileMock.ts
> +      thumbnail_picture: ["https://picsum.photos/seed/post1/800/600"],
done

2024-12-13 09:27 UTC, yashrajoria3 commented on src/server/routers/post.ts
> +  // getPosts: publicProcedure
done

2024-12-13 11:24 UTC, thekalamanchofficial approved these changes

2024-12-13 11:24 UTC, merged